#!/usr/bin/env python3
"""Build realm-index.yml: every public realm in embabel-worlds, as one document an appliance reads.

    GITHUB_TOKEN=... python3 scripts/build-realm-index.py > realm-index.yml

An appliance with no GitHub token used to find its installable realms by scanning GitHub's API,
which allows 60 anonymous requests an hour per public IP address. Every appliance on a network
shares that, so a second install on the same network could see no realms at all. The index is
fetched once, from raw.githubusercontent.com, which that limit does not cover; the assistant reads
it through `assistant.directory.realm-index-url` (IndexedRealmSource).

The listing needs the API, so this runs where a token is: the realm-index workflow, on a schedule.
Each realm's own realm.yml supplies its description, version, author, tags and maturity, read from
raw.githubusercontent.com rather than the API. A repo with no realm.yml is not a realm anyone can
install, and is left out; so are archived repos and the names the assistant already refuses
(GitHubRealmDirectoryProperties.DEFAULT_EXCLUDED_REALMS).
"""
import json
import os
import sys
import urllib.error
import urllib.request

import yaml

ORG = "embabel-worlds"
PREFIXES = ("realm-", "pack-")
EXCLUDED = {"spec", "swift", "js", "core", "java", "dotnet", "kotlin", "cocoa", "dart"}
FIELDS = ("version", "author", "maturity")


def get(url, token=None):
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "embabel-realm-index"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=30) as r:
        return r.read().decode()


def repos(token):
    page = 1
    while True:
        batch = json.loads(get(f"https://api.github.com/orgs/{ORG}/repos?type=public&per_page=100&page={page}", token))
        if not batch:
            return
        yield from batch
        page += 1


def stripped(name):
    for prefix in PREFIXES:
        if name.startswith(prefix):
            return name[len(prefix):]
    return None


def manifest(repo):
    url = f"https://raw.githubusercontent.com/{repo['full_name']}/{repo['default_branch']}/realm.yml"
    try:
        return yaml.safe_load(get(url)) or {}
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return None
        raise


def entry(repo, realm):
    found = {
        "name": stripped(repo["name"]),
        "description": (realm.get("description") or repo.get("description") or "").strip(),
        "source": repo["clone_url"],
        "url": repo["html_url"],
    }
    for field in FIELDS:
        if realm.get(field) not in (None, ""):
            found[field] = str(realm[field])
    tags = [str(t) for t in realm.get("tags") or [] if str(t).strip()]
    if tags:
        found["tags"] = tags
    return found


def main():
    token = os.environ.get("GITHUB_TOKEN", "")
    realms, skipped = [], []
    for repo in repos(token):
        name = stripped(repo["name"])
        if name is None or name in EXCLUDED or repo.get("archived") or repo.get("private"):
            continue
        realm = manifest(repo)
        if realm is None:
            skipped.append(repo["name"])
            continue
        realms.append(entry(repo, realm))
    realms.sort(key=lambda r: r["name"])
    if not realms:
        sys.exit("no realms found — refusing to write an empty index over a good one")
    if skipped:
        print(f"left out (no realm.yml): {', '.join(sorted(skipped))}", file=sys.stderr)
    print("# Generated by scripts/build-realm-index.py — do not edit by hand.")
    print("# Every public realm in embabel-worlds; an appliance reads this instead of scanning GitHub.")
    print(yaml.safe_dump({"realms": realms}, sort_keys=False, allow_unicode=True, width=1000), end="")


if __name__ == "__main__":
    main()
